#!/bin/bash
echo Starting PostgreSQL...
service postgresql start
echo Entering folder...
cd /usr/local/macronizer/latin-macronizer
echo Activating venv...
source .venv/bin/activate
echo Launching API...
python ./api.py
